### ISSUE TITLE
Compile-time messages

### ISSUE THREAD

**Issue by Masterz69** [nrandell/dallasng#13]
```
In file included from src/esphome/components/api/proto.h:4,
                 from src/esphome/components/api/api_pb2.h:5,
                 from src/esphome/components/api/api_connection.h:4,
                 from src/esphome.h:3,
                 from src/main.cpp:3:
src/esphome/components/dallasng/dallasng_temperature_sensor.h: In member function 'bool esphome::dallasng::DallasNgTemperatureSensor::try_get_temperature_c(float*)':
src/esphome/components/dallasng/dallasng_temperature_sensor.h:119:31: warning: format '%d' expects argument of type 'int', but argument 6 has type 'long int' [-Wformat=]
  119 |                 ESP_LOGD(TAG, "'%s' got temperature as %d (%f)", get_name().c_str(), temp, *value);
      |                               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
src/esphome/core/log.h:69:36: note: in definition of macro 'ESPHOME_LOG_FORMAT'
   69 | #define ESPHOME_LOG_FORMAT(format) format
      |                                    ^~~~~~
src/esphome/core/log.h:149:28: note: in expansion of macro 'esph_log_d'
  149 | #define ESP_LOGD(tag, ...) esph_log_d(tag, __VA_ARGS__)
      |                            ^~~~~~~~~~
src/esphome/components/dallasng/dallasng_temperature_sensor.h:119:17: note: in expansion of macro 'ESP_LOGD'
  119 |                 ESP_LOGD(TAG, "'%s' got temperature as %d (%f)", get_name().c_str(), temp, *value);
      |                 ^~~~~~~~
```

Device: Wemos D1 mini
Compiling on pin D3 (GPIO0).

```
dallasng:
  - pin: 
      number: D3
      mode:
        input: True
        pullup: True
    update_interval: 12s
```

Looks like some issues with debug logging.

**Comment by nrandell** [comment]
Is this related to issue #11 ? - Try now

**Comment by Masterz69** [comment]
When using source: ```github://nrandell/dallasng@nrandell/issue11``` - see no more messages during compilation.

Using ```source: github://nrandell/dallasng``` - same messages.
Performed ```Clean Build Files``` - no changes, messages in log.

In both cases see in log: ```|-- OneWireNg @ 0.13.1+sha.cadd760```.


BTW ```dallasng``` can't find sensors on D5(GPIO14) pin, same time ```dallas``` component see them fine.
```
dallasng:
  - pin: 
      number: D5
      mode:
        input: True
        pullup: True
    update_interval: '12s'
```
Just changing to ```dallas``` and voila - sensors found.
